### ISSUE TITLE
generate my own dataset

### ISSUE THREAD

**Issue by legoc1986** [xiangruhuang/HumanCorresViaLearn2Sync#1]
Hi @xiangruhuang ,
   Thanks a lot for the open source, it is an excellent work. Could also provide instructions or codes for  generating training, like I have motion data from AMASS, I want to simulate the human with motions together with the correspondences to the vertices of SMPL model. Is this what I need: https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/2d127ef3513429a84c49d5cae94986e60eb7d403/src/human_corres/datasets/generate_dgfsurreal5k_scans.py#L100
Best 
Xiaofang

**Comment by xiangruhuang** [comment]
Hi Xiaofang,

Thanks for your interest in our work.

Yes, this script is my own implementation for rendering point clouds from human meshes and preserving the correspondences from the rendered point cloud to the original mesh. Each such script deals with one of the dataset, I would recommend modifying from this script, where human meshes are generated from the SMPL model.

> https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/main/src/human_corres/datasets/generate_surreal_scans.py

Let me know if you encounter any issue. :)

Best,
Xiangru

**Comment by legoc1986** [comment]
Hi @xiangruhuang Thanks for the hint. 
Could you explain the meaning of  [gt_correspondence](https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/2d127ef3513429a84c49d5cae94986e60eb7d403/src/human_corres/datasets/generate_shrec19_scans.py#L86)
I think the correspondences is the generated gt_correspondences. 


I have another question. Could you please provide a demo to show the neural network takes input of one data (only one point cloud, instead of a dateset.)

Best 
Xiaofang

**Comment by xiangruhuang** [comment]
`correspondence` maps scan points to the original mesh (only used for mesh to mesh correspondence task).
`gt_correspondence` maps scan points to the SMPL template mesh.

Sure, I'm willing to write a demo. Let me get back to you in a few days. (Apologies for the delay due to an approaching conference deadline).

**Comment by legoc1986** [comment]
I find here the code for generating correspondences, https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/main/src/geop/geometry/camera.py#L73-L78. Actually the **correspondence** is between the vertices of scan to vertices of SMPL parameterized by body pose and shape. While **gt_correspondence** is between the vertices of scan to vertices of template-SMPL? 

Do I need generate gt_correspondences for training? 
Best
Xiaofang

**Comment by xiangruhuang** [comment]
Hi,

In the line you mentioned https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/2d127ef3513429a84c49d5cae94986e60eb7d403/src/human_corres/datasets/generate_shrec19_scans.py#L86

The script renders a mesh to partial scans, and the mesh may not be generated from SMPL as is the case for many datasets. 
`smpl_corres` maps mesh vertices to SMPL template, and `correspondence` maps scan points to mesh, hence composing them gives you a maps from scan points to SMPL template.

You should get `smpl_corres` from the dataset.

**Comment by legoc1986** [comment]
Thanks for the explain, so how do I obtain the gt_correspondence for my own dataset like this?  
![image](https://user-images.githubusercontent.com/65890806/105065936-b55bbf00-5a7e-11eb-8548-d42ac37e4c2c.png).

Can I training with mesh correspondence as ground truth?
Best regards
Xiaofang

**Comment by xiangruhuang** [comment]
Training on Faust is not ideal as FAUST has only 100 meshes. Usually the training is done on SURREAL dataset, which contains 100K meshes (see [here](https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/main/docs/human/training.md)).

For evaluation on FAUST, see [here](https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/main/docs/human/evaluation.md).

**Comment by legoc1986** [comment]
> Training on Faust is not ideal as FAUST has only 100 meshes. Usually the training is done on SURREAL dataset, which contains 100K meshes (see [here](https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/main/docs/human/training.md)).
> 
> For evaluation on FAUST, see [here](https://github.com/xiangruhuang/HumanCorresViaLearn2Sync/blob/main/docs/human/evaluation.md).

Thanks  for the information
